version: "3.3"
services:
  postgres:
    restart: always
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  beampipe:
    restart: always
    build: .
    depends_on:
      - postgres
    environment:
      JWT_GENERATOR_SIGNATURE_SECRET: pleasePleaseChangeMe
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PORT: 8080
      ENABLE_UI: "true"
    ports:
      - "8080:8080"
