version: "3.3"
services:
  postgres:
    restart: always
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  beampipe:
    restart: always
    image: scalardev/beampipe
    environment:
      JWT_GENERATOR_SIGNATURE_SECRET: pleasePleaseChangeMe
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "8080:8080"
