version: "3.3"
services:
  postgres:
    restart: always
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

