# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Advanced topics
  items:
    - label: 'Custom events'
      link: '/custom-events'
    - label: 'Slack integration'
      link: '/slack-integration'

- label: Links
  items:
  - label: 'Beampipe'
    link: 'https://beampipe.io'

  - label: 'Changelog'
    link: '/changelog'

