
ALTER TABLE event
ALTER COLUMN time TYPE TIMESTAMPTZ;

ALTER TABLE account
ADD COLUMN created_at TIMESTAMPTZ DEFAULT now(),
ADD COLUMN last_login_at TIMESTAMPTZ DEFAULT now();

ALTER TABLE domain
ADD COLUMN created_at TIMESTAMPTZ DEFAULT now();