# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/graphql"
  to = "https://api.beampipe.io/graphql"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
