name: CI

on: [push]

env:
  DOCKER_SERVER: rg.fr-par.scw.cloud
  DOCKER_REPO: rg.fr-par.scw.cloud/alysis
  DOCKER_USERNAME: alexsparrow
  DOCKER_PASSWORD: ${{ secrets.SCALEWAY_SECRET }}
jobs:
  server:
    runs-on: ubuntu-latest
    container: alexsparrow/wat-builder
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
         echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_USERNAME --password-stdin $DOCKER_SERVER
         wget -q -O geolite2.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=kfhdgwWCgGixOFlA&suffix=tar.gz"
         tar xf geolite2.tar.gz
         mv GeoLite2* geolite2

         ./gradlew server:jib --no-daemon --console=plain --image=$DOCKER_REPO/server:$GITHUB_RUN_NUMBER

  ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
         echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_USERNAME --password-stdin $DOCKER_SERVER
         cd ./ui
         docker build -t $DOCKER_REPO/web:$GITHUB_RUN_NUMBER .
         docker push $DOCKER_REPO/web:$GITHUB_RUN_NUMBER

  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd web
        yarn
        yarn build
        yarn run next export
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: |
          web/out/

  web-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download math result for job 2
      uses: actions/download-artifact@v2
      with:
        name: website

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: web/out # The folder the action should deploy.

