name: CI

on: [push]

env:
  GEOLITE2_LICENSE_KEY: ${{ secrets.GEOLITE2_LICENSE_KEY }}
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      # if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build
      run: |
        wget -q -O geolite2.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$GEOLITE2_LICENSE_KEY&suffix=tar.gz"
        tar xf geolite2.tar.gz
        mv GeoLite2* geolite2
        ./gradlew --no-daemon --console=plain -P build-ui server:build jibDockerBuild

    - name: Push
      # if: github.ref == 'refs/heads/master'
      run: |
        ./gradlew --no-daemon --console=plain -P build-ui server:jib --image=scalardev/beampipe:$GITHUB_RUN_NUMBER -Djib.to.tags=latest

  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
         cd ./web
         yarn
         yarn build

  ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build
      run: |
        cd ui
        docker build -t scalardev/beampipe-ui:$GITHUB_RUN_NUMBER .

    - name: Push
      if: github.ref == 'refs/heads/master'
      run: |
        docker push scalardev/beampipe-ui:$GITHUB_RUN_NUMBER
