# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/domain/*"
  to = "https://app.beampipe.io/domain/:splat"
  status = 301

[[redirects]]
  from = "/event"
  to = "https://api.beampipe.io/event"
  status = 200
